exclude:
  - "node_modules"
  - "**/*.before.css"
  - "**/README.md"
  - "*.bat"
  - "*.before.css"
  - "*.config.js"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "package-lock.json"
  - "package.json"
  - "README.md"
  - "handout_maker"
sass:
  load_paths:
    - _sass
    - node_modules
title: "Glaceon-471のツール置き場"

titles:
  ccfolia_export: "キャラシート変換ツール"
  handout_maker: "ハンドアウト自動生成ツール"
